<?php
require_once 'config/admin.php'; require_once 'config/conexion.php';
$tipo=$_GET['tipo']??'alumnos'; $formato=$_GET['formato']??'csv';
$map=[
 'alumnos'=>['titulo'=>'Alumnos','sql'=>"SELECT a.ID_Alumno AS ID, a.Nombre, a.Apellido, u.Email, a.Telefono, a.Fecha_nacimiento FROM ALUMNO a JOIN USUARIO u ON u.ID_Usuario=a.ID_Usuario ORDER BY a.Apellido,a.Nombre"],
 'pagos'=>['titulo'=>'Pagos','sql'=>"SELECT p.ID_Pago, CONCAT(a.Nombre,' ',a.Apellido) Alumno,p.Tipo,p.Fecha,p.Importe,p.Estado,p.Metodo_pago FROM PAGO p JOIN ALUMNO a ON a.ID_Alumno=p.ID_Alumno ORDER BY p.Fecha DESC"],
 'asistencia'=>['titulo'=>'Asistencia','sql'=>"SELECT x.Fecha,CONCAT(a.Nombre,' ',a.Apellido) Alumno,g.Nombre Grupo,x.Estado,x.Observacion FROM ASISTENCIA x JOIN ALUMNO a ON a.ID_Alumno=x.ID_Alumno JOIN GRUPO g ON g.ID_Grupo=x.ID_Grupo ORDER BY x.Fecha DESC"],
 'seminarios'=>['titulo'=>'Seminarios','sql'=>"SELECT s.ID_Seminario,COALESCE(NULLIF(s.Nombre,''),s.Titulo) Nombre,s.Fecha,s.Costo,s.Lugar,s.Cupo FROM SEMINARIO s ORDER BY s.Fecha DESC"],
]; if(!isset($map[$tipo])) die('Tipo no válido'); $rows=$conexion->query($map[$tipo]['sql'])->fetchAll(PDO::FETCH_ASSOC);
if($formato==='csv'){header('Content-Type:text/csv; charset=utf-8');header('Content-Disposition:attachment; filename="vilamir_'.$tipo.'.csv"');$out=fopen('php://output','w');if($rows){fputcsv($out,array_keys($rows[0]),';');foreach($rows as $r)fputcsv($out,$r,';');}fclose($out);exit;}
if($formato==='xls'){header('Content-Type:application/vnd.ms-excel; charset=utf-8');header('Content-Disposition:attachment; filename="vilamir_'.$tipo.'.xls"');echo '<table border="1"><tr>';foreach(array_keys($rows[0]??['Sin datos']) as $h)echo '<th>'.htmlspecialchars($h).'</th>';echo '</tr>';foreach($rows as $r){echo '<tr>';foreach($r as $v)echo '<td>'.htmlspecialchars((string)$v).'</td>';echo '</tr>';}echo '</table>';exit;}
?><!doctype html><html lang="es"><head><meta charset="utf-8"><title><?=htmlspecialchars($map[$tipo]['titulo'])?></title><style>body{font-family:Arial;padding:30px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #aaa;padding:7px}th{background:#eee}@media print{.no-print{display:none}}</style></head><body><button class="no-print" onclick="window.print()">Guardar como PDF</button><h1><?=htmlspecialchars($map[$tipo]['titulo'])?> - VILAMIR</h1><table><tr><?php foreach(array_keys($rows[0]??['Sin datos']) as $h): ?><th><?=htmlspecialchars($h)?></th><?php endforeach; ?></tr><?php foreach($rows as $r): ?><tr><?php foreach($r as $v): ?><td><?=htmlspecialchars((string)$v)?></td><?php endforeach; ?></tr><?php endforeach; ?></table></body></html>
