<?php
require_once 'config/autenticacion.php';
if (($_SESSION['usuario_rol'] ?? '') !== 'Profesor') { header('Location: index.php'); exit; }
$nombre = $_SESSION['usuario_nombre'] ?? 'Profesor';
?>
<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Mi espacio docente | VILAMIR</title><link rel="stylesheet" href="css/style.css">
<style>
/* El espacio docente reutiliza el sistema visual de Mi cuenta del alumno */
.teacher-shell{max-width:1240px;margin:34px auto 64px;padding:0 22px;color:var(--text-color,#f5f5f5)}
.teacher-welcome{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:32px;border-radius:22px;background:linear-gradient(120deg,#171717 0%,#262626 70%,#4b1015 100%);border:1px solid rgba(255,255,255,.09);box-shadow:0 16px 40px rgba(0,0,0,.18);margin-bottom:22px}
.teacher-welcome h1{margin:8px 0;font-size:clamp(1.8rem,4vw,2.6rem)}.teacher-welcome p{margin:0;color:#ddd;max-width:650px}.teacher-eyebrow,.teacher-kicker{font-size:.76rem;letter-spacing:.14em;font-weight:800;color:#ff6b73}.teacher-actions{display:flex;gap:10px;flex-wrap:wrap}.teacher-btn{display:inline-flex;align-items:center;justify-content:center;padding:11px 15px;border-radius:10px;text-decoration:none;background:#c92332;color:#fff;font-weight:700;border:1px solid #c92332}.teacher-btn.secondary{background:#202020;border-color:#555}.teacher-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px;margin:20px 0 24px}.teacher-stat{padding:20px;border-radius:17px;background:#191919;border:1px solid #343434;box-shadow:0 8px 24px #0002}.teacher-stat .stat-icon{font-size:1.45rem}.teacher-stat strong{display:block;font-size:1.8rem;margin:8px 0 4px;color:#fff}.teacher-stat span{color:#c6c6c6;font-size:.92rem}.teacher-layout{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;margin-bottom:20px}.teacher-panel{padding:23px;border-radius:18px;background:#191919;border:1px solid #333;box-shadow:0 8px 26px #0002;min-width:0}.teacher-panel.full{margin-bottom:20px}.teacher-panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:18px}.teacher-panel-head h2{margin:5px 0 0;font-size:1.25rem}.teacher-link{color:#ff747d;text-decoration:none;font-weight:700;white-space:nowrap}.teacher-subtitle{color:#bcbcbc;margin:8px 0 16px;font-size:.92rem}.teacher-empty{padding:18px;border-radius:12px;background:#222;color:#c9c9c9;border:1px dashed #454545}.teacher-toolbar{display:flex;gap:10px;flex-wrap:wrap;align-items:center}.teacher-toolbar select,.teacher-toolbar input{background:#242424;color:#fff;border:1px solid #484848;padding:10px 12px;border-radius:9px}.teacher-panel button{cursor:pointer}.teacher-panel .cards-grid,.teacher-panel .timeline,.teacher-panel .calendar{min-width:0}.teacher-panel .section-head{margin-bottom:15px}.teacher-panel .attendance-list{margin-top:16px}.teacher-panel #mensajeProfesorPortal,.teacher-panel #mensajeAsistencia{color:#ff8b92}.teacher-panel #btnGuardarDisciplinasProfesor{margin-top:14px}.teacher-calendar-wrap{overflow-x:auto;padding-bottom:5px}.teacher-calendar-wrap .calendar{min-width:650px}
.teacher-notifications{display:grid;gap:10px}.teacher-notification{display:flex;gap:12px;align-items:flex-start;padding:14px;border:1px solid #383838;border-radius:12px;background:#222}.teacher-notification.read{opacity:.72}.teacher-notification strong{display:block}.teacher-notification p{margin:5px 0;color:#ccc}.teacher-notification small{color:#aaa}.teacher-notification button{background:#333;color:#fff;border:1px solid #555;border-radius:8px;padding:8px 10px}.teacher-summary-layout{margin-bottom:20px}.teacher-summary-card{padding:22px;border-radius:18px;background:#191919;border:1px solid #333;box-shadow:0 8px 26px #0002}.teacher-summary-card h2{margin:6px 0}.teacher-summary-card p{color:#bbb}.teacher-summary-icon{font-size:1.7rem}.teacher-progress{height:9px;background:#303030;border-radius:99px;overflow:hidden;margin:12px 0 8px}.teacher-progress span{display:block;height:100%;background:#c92332;border-radius:inherit}.teacher-group-summary{display:grid;gap:12px}.teacher-group-row{display:grid;grid-template-columns:minmax(180px,1.5fr) minmax(130px,2fr) auto;gap:16px;align-items:center;padding:15px;border-radius:12px;background:#222;border:1px solid #383838}.teacher-group-row strong{display:block}.teacher-group-row small{display:block;color:#aaa;margin-top:4px}.teacher-capacity{font-weight:700;white-space:nowrap}.teacher-capacity.ok{color:#8ee6a1}.teacher-capacity.full{color:#ff7c84}@media(max-width:650px){.teacher-group-row{grid-template-columns:1fr}.teacher-capacity{white-space:normal}}
@media(max-width:850px){.teacher-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.teacher-layout{grid-template-columns:1fr}.teacher-welcome{align-items:flex-start;flex-direction:column}}
@media(max-width:480px){.teacher-shell{padding:0 13px;margin-top:20px}.teacher-welcome,.teacher-panel{padding:18px}.teacher-stats{gap:10px}.teacher-stat{padding:15px}.teacher-stat strong{font-size:1.5rem}.teacher-actions{width:100%}.teacher-btn{flex:1}}
</style>
</head>
<body class="account-page">
<header class="navbar"><div class="logo">VILAMIR</div><nav><a href="index.php">Inicio</a><a class="active" href="profesor.php">Mi espacio</a><a href="horarios.php">Mi cronograma</a><a href="calendario.php">Calendario</a><a href="grupos.php">Grupos</a><a href="seminarios.php">Eventos</a><a href="logout.php">Cerrar sesión</a></nav></header>
<main class="teacher-shell">
<section class="teacher-welcome"><div><span class="teacher-eyebrow">MI ESPACIO DOCENTE</span><h1>Hola, <?= htmlspecialchars($nombre, ENT_QUOTES, 'UTF-8') ?> 👋</h1><p>Tu jornada, tus grupos y el seguimiento de tus alumnos, organizados en un solo lugar.</p></div><div class="teacher-actions"><a class="teacher-btn" href="calendario.php">📅 Ver calendario</a><a class="teacher-btn secondary" href="horarios.php">🗓️ Mi cronograma</a></div></section>
<section id="profStats" class="teacher-stats"></section>
<section id="profResumen" class="teacher-layout teacher-summary-layout"></section>
<div class="teacher-layout">
<section class="teacher-panel"><div class="teacher-panel-head"><div><span class="teacher-kicker">AGENDA</span><h2>📅 Mis próximas clases</h2></div><a class="teacher-link" href="calendario.php">Ver calendario →</a></div><div id="proximasProfesor" class="timeline"><div class="teacher-empty">Cargando tus próximas clases…</div></div></section>
<section class="teacher-panel"><div class="teacher-panel-head"><div><span class="teacher-kicker">ORGANIZACIÓN</span><h2>👥 Mis grupos</h2></div><a class="teacher-link" href="grupos.php">Ver grupos →</a></div><div id="listaGruposProfesor" class="cards-grid"><div class="teacher-empty">Cargando grupos…</div></div></section>
</div>
<section class="teacher-panel full"><div class="teacher-panel-head"><div><span class="teacher-kicker">AVISOS</span><h2>🔔 Notificaciones</h2><p class="teacher-subtitle">Cambios de horarios y avisos relacionados con tus grupos.</p></div><button class="teacher-btn secondary" type="button" id="marcarNotifProfesor">Marcar todas como leídas</button></div><div id="notificacionesProfesor" class="teacher-notifications"><div class="teacher-empty">Cargando notificaciones…</div></div></section>
<section class="teacher-panel full"><div class="teacher-panel-head"><div><span class="teacher-kicker">PERFIL DOCENTE</span><h2>🥋 Disciplinas que enseño</h2><p class="teacher-subtitle">Seleccioná las disciplinas que podés enseñar. La asignación de grupos se administra por separado.</p></div></div><div id="listaDisciplinasProfesor" class="cards-grid"><div class="teacher-empty">Cargando disciplinas…</div></div><button id="btnGuardarDisciplinasProfesor" class="teacher-btn">Guardar disciplinas</button><p id="mensajeProfesorPortal" role="status" aria-live="polite"></p></section>
<section class="teacher-panel full"><div class="teacher-panel-head"><div><span class="teacher-kicker">PLANIFICACIÓN</span><h2>🗓️ Mi semana de trabajo</h2></div><a class="teacher-link" href="calendario.php">Calendario completo →</a></div><div class="teacher-calendar-wrap"><div id="calendarioProfesor" class="calendar"><div class="teacher-empty">Cargando calendario…</div></div></div></section>
<section class="teacher-panel full attendance-panel"><div class="teacher-panel-head"><div><span class="teacher-kicker">SEGUIMIENTO</span><h2>✅ Control de asistencia</h2><p class="teacher-subtitle">Elegí el grupo y la fecha para registrar la asistencia de tus alumnos.</p></div></div><div class="teacher-toolbar"><select id="grupoAsistencia"><option value="">Seleccionar grupo</option></select><input type="date" id="fechaAsistencia"><button id="cargarAsistencia" class="teacher-btn">Cargar alumnos</button></div><div id="listaAsistencia" class="attendance-list"></div><button id="guardarAsistencia" class="teacher-btn" style="display:none">Guardar asistencia</button><p id="mensajeAsistencia" role="status" aria-live="polite"></p></section>
<section class="teacher-panel full"><div class="teacher-panel-head"><div><span class="teacher-kicker">RESUMEN DE GRUPOS</span><h2>📊 Ocupación de mis grupos</h2><p class="teacher-subtitle">Cantidad de alumnos activos y cupos disponibles en cada grupo asignado.</p></div></div><div id="resumenGruposProfesor" class="teacher-group-summary"></div></section>
<section class="teacher-panel full"><div class="teacher-panel-head"><div><span class="teacher-kicker">COMUNICACIONES</span><h2>🔔 Avisos de la academia</h2><p class="teacher-subtitle">Cambios de organización y mensajes enviados por administración.</p></div><button type="button" class="teacher-btn secondary" onclick="cargarAvisosProfesor()">Actualizar</button></div><div id="avisosProfesor" class="teacher-group-summary"><div class="teacher-empty">Cargando avisos…</div></div></section>
</main><footer>© 2026 VILAMIR · Enseñanza práctica de artes marciales</footer><script src="js/profesor.js"></script>    <script src="js/mobile.js"></script>
</body></html>
